### ISSUE TITLE
IndexError: list index out of range.

### ISSUE THREAD

**Issue by starinspace** [thrkll/ruv-dl#1]
I did try the latest version, it worked untill today.

Traceback (most recent call last):
  File "ruv-dl.py", line 109, in <module>
    main()
  File "ruv-dl.py", line 8, in main
    link()
  File "ruv-dl.py", line 20, in link
    api()
  File "ruv-dl.py", line 30, in api
    api.url = 'https://api.ruv.is/api/programs/program/' + episode_code[0] + '/' + episode_code[1]
IndexError: list index out of range

**Comment by thrkll** [comment]
Apparently RUV changed their links a bit. This has now been fixed and the latest version works as before.
